### ISSUE TITLE
Kinetic-Swift auditor and Kinetic-Swift-updater are terminated when Kinetic ring cannot be reached

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#40]
Customers comments:
When a Kinetic device registered in a object ring becomes out of service or unreachable, kinetic-swift-auditor and kinetic-swift-updater are terminated.  Customer expects these services to continue with the other Kinetic devices.  It would otherwise cumbersome to manually start those services on every malfunctioning kinetic device.

**Comment by clayg** [comment]
Yeah I think the auditor and updater need a bit more functional/failure testing - hopefull the replicator does a little better - although operational experience will inform there as well.

For these kind of things Tracebacks from the log would be super helpful.
