### ISSUE TITLE
Kinetic-Swift-replicator repeatedly dumps "Too many open files" error messages onto swift.log after 30-40mins idle time of kinetic-swift system

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#41]
Customers comment:
"Customer observed kinetic-swift-replicator repeatedly dumps "Too many open files" error messages onto swift.log after 30-40mins idle time of kinetic-swift system.  They know that a kernel parameter can increase the max number of open fid per process, but they believe the "Too many open files" should be fixed since it implies there's some deficiency in resource management at kinetic-swift."

**Comment by clayg** [comment]
Sounds like a duplicate of issue #34 which was closed in the last couple of weeks.  @mayurshetty can you verify this behavior with the latest code?

**Comment by clayg** [comment]
@mayurshetty can you let me know if you need some more time to confirm this - or should I just close it for now and we can reopen if need be?

**Comment by mayurshetty** [comment]
yes, give us another week to confirm the fix. thanks!

**Comment by mayurshetty** [comment]
@clayg the customer confirmed that the fix works, please feel free to close it.
