### ISSUE TITLE
Removing a Kinetic device from the ring does not work

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#42]
Removing a Kinetic device from the object ring does not work

kinetic-linux:/etc/swift$ swift-ring-builder object.builder
object.builder, build version 3
1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 3 devices, 100.00 balance
The minimum number of hours before a partition can be reassigned is 1
Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
             0       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.70.239:8123   1.00          0 -100.00 
             1       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.70.19:8123   1.00          0 -100.00 
             2       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.71.15:8123   1.00          0 -100.00 

Tried removing the Kinetic-device using IP_Address:Port, but that didn’t work
kinetic-linux:/etc/swift$ swift-ring-builder object.builder remove 10.24.70.239:8123
Search value "10.24.70.239:8123" matched 0 devices.
The on-disk ring builder is unchanged.

Tried just the IP address of the drive, of that failed too.
kinetic-linux:/etc/swift$ swift-ring-builder object.builder remove 10.24.70.239
Search value "10.24.70.239" matched 0 devices.
The on-disk ring builder is unchanged.

Tried using the Device id, but that didn’t work either.
kinetic-linux:/etc/swift$ swift-ring-builder object.builder remove 0
Search value "0" matched 0 devices.
The on-disk ring builder is unchanged.

**Comment by clayg** [comment]
this is the same as issue #43

**Comment by clayg** [comment]
if you're still having problems removing the device when searching with the `--device` option - please re-open.
