### ISSUE TITLE
Searching for a Kinetic device in the ring does not work

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#43]
This is probably related to issue# 42
https://github.com/swiftstack/kinetic-swift/issues/42

kinetic-linux:/etc/swift$ swift-ring-builder object.builder 
object.builder, build version 3
1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 3 devices, 100.00 balance
The minimum number of hours before a partition can be reassigned is 1
Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
             0       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.70.239:8123   1.00          0 -100.00 
             1       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.70.19:8123   1.00          0 -100.00 
             2       1     1       127.0.0.1  6000       127.0.0.1              6000 10.24.71.15:8123   1.00          0 -100.00

Search using the IP_Address or IP_Address:8123 both don’t work

kinetic-linux:/etc/swift$ swift-ring-builder object.builder search 10.24.70.19
No matching devices found

kinetic-linux:/etc/swift$ swift-ring-builder object.builder search 10.24.70.19:8123
No matching devices found

**Comment by clayg** [comment]
You can most easily identify devices using the `--device` option:

    $ swift-ring-builder kinetic.builder
    kinetic.builder, build version 8
    1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 8 devices, 0.00 balance, 0.00 dispersion
    The minimum number of hours before a partition can be reassigned is 1
    The overload factor is 0.00% (0.000000)
    Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
                 0       1     1       127.0.0.1  6010       127.0.0.1              6010 127.0.0.1:8010   1.00        384    0.00 
                 1       1     1       127.0.0.1  6010       127.0.0.1              6010 127.0.0.1:8011   1.00        384    0.00 
                 2       1     1       127.0.0.1  6020       127.0.0.1              6020 127.0.0.1:8020   1.00        384    0.00 
                 3       1     1       127.0.0.1  6020       127.0.0.1              6020 127.0.0.1:8021   1.00        384    0.00 
                 4       1     1       127.0.0.1  6030       127.0.0.1              6030 127.0.0.1:8030   1.00        384    0.00 
                 5       1     1       127.0.0.1  6030       127.0.0.1              6030 127.0.0.1:8031   1.00        384    0.00 
                 6       1     1       127.0.0.1  6040       127.0.0.1              6040 127.0.0.1:8040   1.00        384    0.00 
                 7       1     1       127.0.0.1  6040       127.0.0.1              6040 127.0.0.1:8041   1.00        384    0.00 
    $ swift-ring-builder kinetic.builder search --device 127.0.0.1:8010
    Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
                 0       1     1       127.0.0.1  6010       127.0.0.1              6010 127.0.0.1:8010   1.00        384    0.00 
    $ swift-ring-builder kinetic.builder remove --device 127.0.0.1:8010
    d0r1z1-127.0.0.1:6010R127.0.0.1:6010/127.0.0.1:8010_"" marked for removal and will be removed next rebalance.
