### ISSUE TITLE
Use of KeyRange in _unlink_old orphans some chunk keys

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#47]
Old tombstone keys are still there after reclaim_age. The reclaim_age was set to 600 for the account, container and object services.

    account-server.conf:
    reclaim_age = 600

    container-server.conf:
    reclaim_age = 600

    object-server.conf:
    reclaim_age = 600

Here is the test case to reproduce the issue:

    [root@paco04 TEST]# dd if=/dev/urandom of=Object-5GiB+3bytes count=5242880 bs=1024
    5242880+0 records in
    5242880+0 records out
    5368709120 bytes (5.4 GB) copied, 530.609 s, 10.1 MB/s
    [root@paco04 TEST]#
    [root@paco04 TEST]# echo -n "123" >> Object-5GiB+3bytes
    [root@paco04 TEST]# ls -l Object-5GiB+3bytes
    -rw-r--r--. 1 root root 5368709123 Jun 26 14:38 Object-5GiB+3bytes
    [root@paco04 TEST]#  swift upload UploadTest Object-5GiB+3bytes --segment-size 2147483648
    Object-5GiB+3bytes segment 2
    Object-5GiB+3bytes segment 1
    Object-5GiB+3bytes segment 0
    Object-5GiB+3bytes
    [root@paco04 TEST]# swift stat UploadTest Object-5GiB+3bytes
           Account: AUTH_eb2ea9573cbb4efc82d12df60d62e130
         Container: UploadTest
            Object: Object-5GiB+3bytes
      Content Type: application/octet-stream
    Content Length: 5368709123
     Last Modified: Fri, 26 Jun 2015 07:41:54 GMT
              ETag: "d001bc21a1253ff7b3b53bb7269fcbd1"
          Manifest: UploadTest_segments/Object-5GiB%2B3bytes/1435304332.665138/5368709123/2147483648/
        Meta Mtime: 1435304332.665138
     Accept-Ranges: bytes
        Connection: keep-alive
       X-Timestamp: 1435304513.62356
        X-Trans-Id: tx3f6b539b6b7f47ee8cac3-00558d0248
    [root@paco04 TEST]# swift list UploadTest
    Object-0byte
    Object-1MiB+1byte
    Object-5GiB+3bytes
    [root@paco04 TEST]# swift list UploadTest_segments
    Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000000
    Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000001
    Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000002
    [root@paco04 TEST]# kineticc -H kinetic04 -P 8123 list objects | gawk -F . '{ if ($5 == "data") print; }' | sort -t . -k 3,4 | tail -n 4
    objects.079e5bfba01969ff170a936ff886f4c9.1435304370.17025.data.02ac08ec-4608-4ef6-8e52-49c70b2a4953
    objects.a920a96a7612a71118ef773617f99686.1435304370.28019.data.369bc1e9-d5af-4763-9b04-7d9207237ff0
    objects.0290fa7b173bf445a44dc10aaf755716.1435304370.94539.data.67f5ae51-8c58-4e36-922f-2d9da42344b1
    objects.0224cc6900939eb615d389ab7619568f.1435304513.62356.data.19ebe6a7-c75a-4d18-baf4-7eaba2fe88e0
    [root@paco04 TEST]# 079e5bfba01969ff170a936ff886f4c9^C
    [root@paco04 TEST]# kineticc -H kinetic04 -P 8123 list chunks
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000001
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000002
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000003
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000004
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000005
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000006
    ...
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000195
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000196
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000197
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000198
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000199
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000200
    [root@paco04 TEST]#
    [root@paco04 TEST]# md5sum Object-5GiB+3bytes
    fd47cd90baa33c5092a49620f90c24b4  Object-5GiB+3bytes
    [root@paco04 TEST]# swift download UploadTest Object-5GiB+3bytes --output DownloadObject-5GiB+3bytes
    Object-5GiB+3bytes [auth 0.738s, headers 0.976s, total 130.853s, 41.261 MB/s]
    [root@paco04 TEST]# md5sum DownloadObject-5GiB+3bytes
    fd47cd90baa33c5092a49620f90c24b4  DownloadObject-5GiB+3bytes
    [root@paco04 TEST]# swift delete UploadTest Object-5GiB+3bytes
    UploadTest_segments/Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000000
    UploadTest_segments/Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000001
    UploadTest_segments/Object-5GiB+3bytes/1435304332.665138/5368709123/2147483648/00000002
    Object-5GiB+3bytes
    [root@paco04 TEST]#
    [root@paco04 TEST]# kineticc -H kinetic04 -P 8123 list objects
    objects.0224cc6900939eb615d389ab7619568f.1435306076.38825.ts.c91ee251-589d-4ac2-85fa-2daf79bc2516
    objects.0290fa7b173bf445a44dc10aaf755716.1435306078.20170.ts.9faae8d1-3cbc-42f1-8994-21b525693f88
    objects.079e5bfba01969ff170a936ff886f4c9.1435306077.38963.ts.ba81f692-dd26-42dc-8963-e8b02973cfab
    objects.5338f62b4e718aee7a803ed44050a974.1435303680.87586.data.d76cc0c8-2945-4b9c-9c11-c4eda260519d
    objects.a920a96a7612a71118ef773617f99686.1435306077.25919.ts.f199dd4c-ed2a-4142-917c-eba944d76bff
    objects.c859425eda0f1f7109b41f4aae420e83.1435303513.31478.data.fa60745b-5d3e-4585-98a1-fe6ca783210c
    [root@paco04 TEST]# kineticc -H kinetic04 -P 8123 list chunks
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000201
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000202
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000203
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000204
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000205
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000206
    ...
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000397
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000398
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000399
    chunks.0290fa7b173bf445a44dc10aaf755716.67f5ae51-8c58-4e36-922f-2d9da42344b1.00000000000000000000000000000400

**Comment by clayg** [comment]
There was so much output I didn't quite understand the issue at first.

The `_unlink_old` method in the obj.server needs to be updated to use paged-marker queries like the replicator does in `iter_all_objects`.

**Comment by pauldardeau** [comment]
@clayg please clarify the comment about paged-marker queries.
