### ISSUE TITLE
Are tombstones deleted?

### ISSUE THREAD

**Issue by pauldardeau** [swiftstack/kinetic-swift#50]
After deleting objects, I see tombstone entries, but I don't see them being cleaned up.  Is this configurable?  How can I exercise the tombstone cleanup to verify that they're deleted?

**Comment by clayg** [comment]
Tombstones have to hang around long enough to prevent dead data from being reintroduced to the cluster, but the normally get cleaned up after reclaim_age (which defaults to a week or two).

I think that feature is missing:
https://github.com/swiftstack/kinetic-swift/blob/master/kinetic_swift/obj/replicator.py#L77

Looking at it again, seems like split_key would need to pull the `ext` out of the parts list - then return that as part of the map.  Then `if key_info['ext'] == 'ts' and key_info['timestamp'] < now - reclaim_age` you can reap it.
