### ISSUE TITLE
Kinetic Swiftstack Controller doc bug

### ISSUE THREAD

**Issue by mayurshetty** [swiftstack/kinetic-swift#57]
The Hardware Requirements page of the docs https://kinetic.swiftstack.com/docs/admin/hardware.html has not been updated to reflect a Kinetic-Swift deployment.

**Comment by clayg** [comment]
This issue is related to the SwiftStack product - not the kinetic-swift project.  I'm not sure where to capture this issue for now - especially since we're still trying to learn what the hardware recommendations should be for setting up kinetic-swift.

**Comment by clayg** [comment]
ok, I'm calling it - file issues with kinetic.swiftstack.com through zendesk.
