### ISSUE TITLE
Duplicate objects from replicator

### ISSUE THREAD

**Issue by pauldardeau** [swiftstack/kinetic-swift#60]
Replicator creates a new object on a drive if the drive was temporarily unavailable while the object was updated. In this case the 'old' object remains on the drive (both an old and new version of same object). Is this the intended behavior? When would the duplicate of object be removed (the old one)?

Test procedure and log:

    [root@paco01 work]# echo Object-1 > Object-1
    [root@paco01 work]# swift upload ReplicatorTest Object-1
    Object-1
    [root@paco01 work]# kineticc -H kinetic01 -P 8123 list objects | gawk -F . '{ if ($5 == "data") print; }' | sort -t . -k 3,4 | tail -n 1
    objects.ea8fd3c6fc5583b3068aee263f5329fc.1437636904.90798.data.bfb87b1e-9c9f-488d-88cf-a8b83f4190a6
    [root@paco01 work]# kineticc -H kinetic01 -P 8123 list chunks.ea8fd3c6fc5583b3068aee263f5329fc
    chunks.ea8fd3c6fc5583b3068aee263f5329fc.bfb87b1e-9c9f-488d-88cf-a8b83f4190a6.00000000000000000000000000000001
    [root@paco01 work]# JAVA_HOME=/usr/lib/jvm/jre /opt/kinetic-java-tools/kinetic-tools/bin/ktool.sh -lockdevice -pin "" -in /opt/kinetic-java-tools/kinetic-tools/out/kinetic01
    Total(Succeed/Failed): 1(1/0)
    Result has been persisted to /opt/kinetic-java-tools/kinetic-tools/out/lockdevice_1437637151063
    [root@paco01 work]# swift post ReplicatorTest Object-1 -m XXX:test
    [root@paco01 work]# kineticc -H kinetic05 -P 8123 list objects.ea8fd3c6fc5583b3068aee263f5329fc
    objects.ea8fd3c6fc5583b3068aee263f5329fc.1437637172.60692.data.03dec53f-2a25-46d4-a5b3-a98ef910a6fc
    [root@paco01 work]# kineticc -H kinetic05 -P 8123 list chunks.ea8fd3c6fc5583b3068aee263f5329fc
    chunks.ea8fd3c6fc5583b3068aee263f5329fc.03dec53f-2a25-46d4-a5b3-a98ef910a6fc.00000000000000000000000000000001
    [root@paco01 work]# kineticc -H kinetic09 -P 8123 list objects.ea8fd3c6fc5583b3068aee263f5329fc
    objects.ea8fd3c6fc5583b3068aee263f5329fc.1437637172.60692.data.f11a2f96-c62a-44bf-b9f5-d41c3916e008
    [root@paco01 work]# kineticc -H kinetic09 -P 8123 list chunks.ea8fd3c6fc5583b3068aee263f5329fc
    chunks.ea8fd3c6fc5583b3068aee263f5329fc.f11a2f96-c62a-44bf-b9f5-d41c3916e008.00000000000000000000000000000001
    [root@paco01 work]# JAVA_HOME=/usr/lib/jvm/jre /opt/kinetic-java-tools/kinetic-tools/bin/ktool.sh -unlockdevice -pin "" -in /opt/kinetic-java-tools/kinetic-tools/out/kinetic01
    Total(Succeed/Failed): 1(1/0)
    Result has been persisted to /opt/kinetic-java-tools/kinetic-tools/out/unlockdevice_1437637246762
    [root@paco01 work]# sleep 60
    [root@paco01 work]# kineticc -H kinetic01 -P 8123 list objects.ea8fd3c6fc5583b3068aee263f5329fc
    objects.ea8fd3c6fc5583b3068aee263f5329fc.1437636904.90798.data.bfb87b1e-9c9f-488d-88cf-a8b83f4190a6
    objects.ea8fd3c6fc5583b3068aee263f5329fc.1437637172.60692.data.03dec53f-2a25-46d4-a5b3-a98ef910a6fc
    [root@paco01 work]# kineticc -H kinetic01 -P 8123 list chunks.ea8fd3c6fc5583b3068aee263f5329fc
    chunks.ea8fd3c6fc5583b3068aee263f5329fc.03dec53f-2a25-46d4-a5b3-a98ef910a6fc.00000000000000000000000000000001
    chunks.ea8fd3c6fc5583b3068aee263f5329fc.bfb87b1e-9c9f-488d-88cf-a8b83f4190a6.00000000000000000000000000000001
    [root@paco01 work]# grep -w "object-replicator" /var/log/swift/swift.log | tail -n 100
    Jul 23 14:41:13 <local0.info> localhost object-replicator: Starting object replication pass.
    Jul 23 14:41:13 <local0.info> localhost object-replicator: begining replication pass for '192.168.2.1:8123'
    Jul 23 14:41:13 <local0.info> localhost object-replicator: begining replication pass for '192.168.2.5:8123'
    Jul 23 14:41:13 <local0.info> localhost object-replicator: Successfully replicated 'objects.ea8fd3c6fc5583b3068aee263f5329fc.1437637172.60692.data.03dec53f-2a25-46d4-a5b3-a98ef910a6fc' to '192.168.2.1:8123'
    Jul 23 14:41:13 <local0.info> localhost object-replicator: begining replication pass for '192.168.2.9:8123'
    Jul 23 14:41:13 <local0.info> localhost object-replicator: replication cycle for ['192.168.2.1:8123', '192.168.2.5:8123', '192.168.2.9:8123'] complete
    Jul 23 14:41:13 <local0.info> localhost object-replicator: Object replication complete. (0.00 minutes)

**Comment by clayg** [comment]
I have a notion that this could be detected right here:

https://github.com/swiftstack/kinetic-swift/blob/master/kinetic_swift/obj/replicator.py#L160

with PR #59 in place you could just kill the head key and write a temp_marker, really if there was a way to DiskFile._unlink_old after replicate_object that'd be best.

There's a test that cover's this scenario, but it doesn't assert that the old object is cleaned up:

https://github.com/swiftstack/kinetic-swift/blob/master/test_kinetic_swift/test_replicator.py#L413

You can verify using a connection to source_device that the old object is still on the kinetic disk

**Comment by pauldardeau** [comment]
More details on @clayg note: check can be added along with timestamp comparison in is_object_on_target within replicator.

**Comment by pauldardeau** [comment]
In response to initial report, this is a bug.
