### ISSUE TITLE
Error happened during "vagrant up"

### ISSUE THREAD

**Issue by chenchongli** [swiftstack/kinetic-swift#61]
I am installing the kinetic-swift following "Getting started", error happens during the step of "vagrant up". My system is OSX 10.9.5, I also tried this on Ubuntu 14.04 LTS and OSX 10.11.2, same thing happened. Please see the following error log. Could you please help out about this? Many thanks!

===============================================================================
==> default: Collecting PyECLib>=1.0.7 (from swift==2.3.1.dev236)
==> default:   Downloading PyECLib-1.2.0.tar.gz (6.7MB)
==> default: Installing collected packages: eventlet, PyECLib, swift
==> default:   Found existing installation: eventlet 0.13.0
==> default:     Uninstalling eventlet-0.13.0:
==> default:       Successfully uninstalled eventlet-0.13.0
==> default:   Running setup.py install for PyECLib
==> default:     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-kZk2Hl/PyECLib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-eVFaU0-record/install-record.txt --single-version-externally-managed --compile:
==> default:     running install
==> default:     running build
==> default:     **************************************************************
==> default:     ***
==> default:     *** Can not locate liberasurecode.so.1
==> default:     ***
==> default:     *** Install -
==> default:     ***   Manual: https://bitbucket.org/tsg-/liberasurecode.git
==> default:     ***   Fedora/Red Hat variants: liberasurecode-devel
==> default:     ***   Debian/Ubuntu variants: liberasurecode-dev
==> default:     ***
==> default:     **************************************************************
==> default:     
==> default:     ----------------------------------------
==> default: STDERR: /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
==> default:   InsecurePlatformWarning
==> default: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-kZk2Hl/PyECLib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-eVFaU0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 255 in /tmp/pip-build-kZk2Hl/PyECLib
==> default: ---- End output of pip install -e . && pip install -r test-requirements.txt ----
==> default: Ran pip install -e . && pip install -r test-requirements.txt returned 1
==> default: [2016-01-14T00:30:05+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
===============================================================================

**Comment by clayg** [comment]
Should be fixed in 65056fcbdb9962c2e06ff8c71b0f91fabffa6fb9

**Comment by chenchongli** [comment]
Thank you very much for the fixing. It works great and has passed the step of "pip install -e . && pip install -r test-requirements.txt" now.

Unfortunately, I got another error during "swift-init start main". Could you please help to look into again? Many thanks!

The following is the error log:
-------------------------------------------------------------
==> default:     - execute sudo -u vagrant swift-ring-builder object-1.builder add r1z4-127.0.0.1:6040/sdb8 1 && rm -f /etc/swift/object-1.ring.gz || true
==> default:   * execute[object-1.builder-rebalance] action run
==> default: [2016-01-15T17:59:48+00:00] INFO: execute[Guard resource] ran successfully
==> default:  (skipped due to not_if)
==> default:   * execute[startmain] action run
==> default:     [execute] 
==> default: WARNING: Unable to modify file descriptor limit.  Running as non-root?
==> default:               
==> default: Starting proxy-server...(/etc/swift/proxy-server.conf)
==> default:               
==> default: Starting container-server...(/etc/swift/container-server/1.conf)
==> default:               
==> default: Starting container-server...(/etc/swift/container-server/2.conf)
==> default:               
==> default: Starting container-server...(/etc/swift/container-server/3.conf)
==> default:               
==> default: Starting container-server...(/etc/swift/container-server/4.conf)
==> default:               
==> default: Starting account-server...(/etc/swift/account-server/1.conf)
==> default:               
==> default: Starting account-server...(/etc/swift/account-server/2.conf)
==> default:               
==> default: Starting account-server...(/etc/swift/account-server/3.conf)
==> default:               
==> default: Starting account-server...(/etc/swift/account-server/4.conf)
==> default:               
==> default: Starting object-server...(/etc/swift/object-server/1.conf.d)
==> default:               
==> default: Starting object-server...(/etc/swift/object-server/2.conf.d)
==> default:               
==> default: Starting object-server...(/etc/swift/object-server/3.conf.d)
==> default:               
==> default: Starting object-server...(/etc/swift/object-server/4.conf.d)
==> default:               
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default: 
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:               ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:               
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `run` on resource 'execute[startmain]'
==> default:     
==> default: ================================================================================
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:     
==> default: ------------------------------------
==> default:     
==> default: Expected process to exit with [0], but received '1'
==> default: 
==> default:     
==> default: ---- Begin output of sudo -u vagrant swift-init start main ----
==> default: 
==> default:     
==> default: STDOUT: WARNING: Unable to modify file descriptor limit.  Running as non-root?
==> default: 
==> default:     
==> default: Starting proxy-server...(/etc/swift/proxy-server.conf)
==> default:     Starting container-server...(/etc/swift/container-server/1.conf)
==> default:     Starting container-server...(/etc/swift/container-server/2.conf)
==> default:     Starting container-server...(/etc/swift/container-server/3.conf)
==> default:     Starting container-server...(/etc/swift/container-server/4.conf)
==> default:     Starting account-server...(/etc/swift/account-server/1.conf)
==> default:     Starting account-server...(/etc/swift/account-server/2.conf)
==> default:     Starting account-server...(/etc/swift/account-server/3.conf)
==> default:     Starting account-server...(/etc/swift/account-server/4.conf)
==> default:     Starting object-server...(/etc/swift/object-server/1.conf.d)
==> default:     Starting object-server...(/etc/swift/object-server/2.conf.d)
==> default:     Starting object-server...(/etc/swift/object-server/3.conf.d)
==> default:     Starting object-server...(/etc/swift/object-server/4.conf.d)
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     
==> default:     ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default:     STDERR: 
==> default:     ---- End output of sudo -u vagrant swift-init start main ----
==> default:     Ran sudo -u vagrant swift-init start main returned 1
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/427ddde5340dd5e9d455d6acaf0ce79a/cookbooks/swift/recipes/default.rb
==> default:     
==> default:     
==> default: 255: execute "startmain" do
==> default: 
==> default:     
==> default: 256:   command "sudo -u vagrant swift-init start main"
==> default: 
==> default:     
==> default: 257: end
==> default: 
==> default:     
==> default: 258: 
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Compiled Resource:
==> default:     
==> default: ------------------
==> default: 
==> default:     # Declared in /tmp/vagrant-chef/427ddde5340dd5e9d455d6acaf0ce79a/cookbooks/swift/recipes/default.rb:255:in `from_file'
==> default:     
==> default:     execute("startmain") do
==> default:       action [:run]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :execute
==> default:       command "sudo -u vagrant swift-init start main"
==> default:       backup 5
==> default:       returns 0
==> default:       declared_type :execute
==> default:       cookbook_name :swift
==> default:       recipe_name "default"
==> default:     end
==> default:     
==> default: [2016-01-15T17:59:53+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2016-01-15T17:59:53+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-01-15T17:59:53+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 122 resources updated in 04 minutes 22 seconds
==> default: [2016-01-15T17:59:53+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-01-15T17:59:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-01-15T17:59:53+00:00] ERROR: execute[startmain] (swift::default line 255) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of sudo -u vagrant swift-init start main ----
==> default: STDOUT: WARNING: Unable to modify file descriptor limit.  Running as non-root?
==> default: Starting proxy-server...(/etc/swift/proxy-server.conf)
==> default: Starting container-server...(/etc/swift/container-server/1.conf)
==> default: Starting container-server...(/etc/swift/container-server/2.conf)
==> default: Starting container-server...(/etc/swift/container-server/3.conf)
==> default: Starting container-server...(/etc/swift/container-server/4.conf)
==> default: Starting account-server...(/etc/swift/account-server/1.conf)
==> default: Starting account-server...(/etc/swift/account-server/2.conf)
==> default: Starting account-server...(/etc/swift/account-server/3.conf)
==> default: Starting account-server...(/etc/swift/account-server/4.conf)
==> default: Starting object-server...(/etc/swift/object-server/1.conf.d)
==> default: Starting object-server...(/etc/swift/object-server/2.conf.d)
==> default: Starting object-server...(/etc/swift/object-server/3.conf.d)
==> default: Starting object-server...(/etc/swift/object-server/4.conf.d)
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: 
==> default: ERROR: Invalid Storage Policy Configuration in /etc/swift/swift.conf (Wrong ec_type jerasure_rs_vand for policy ec, should be one of "flat_xor_hd_3, flat_xor_hd_4, liberasurecode_rs_vand")
==> default: STDERR: 
==> default: ---- End output of sudo -u vagrant swift-init start main ----
==> default: Ran sudo -u vagrant swift-init start main returned 1
==> default: [2016-01-15T17:59:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by clayg** [comment]
hrmm... ok we'll i'll test 89581d18044417e1a09f9d7da235b38c1ca8b86f

**Comment by chenchongli** [comment]
Complete successfully!!! Thank you very much, Clay!!!

==> default:   * execute[kinetic-object-start] action run
==> default: 
==> default:     [execute] WARNING: Unable to modify file descriptor limit.  Running as non-root?
==> default:               Starting object-server...(/etc/swift/object-server/1.conf.d)
==> default:               Starting object-server...(/etc/swift/object-server/2.conf.d)
==> default:               Starting object-server...(/etc/swift/object-server/3.conf.d)
==> default:               Starting object-server...(/etc/swift/object-server/4.conf.d)
==> default: [2016-01-15T21:13:44+00:00] INFO: execute[kinetic-object-start] ran successfully
==> default:     - execute sudo -i -u vagrant swift-init object start
==> default: 
==> default: [2016-01-15T21:13:44+00:00] INFO: Chef Run complete in 929.346040777 seconds
==> default: [2016-01-15T21:13:44+00:00] INFO: Skipping removal of unused files from the cache
==> default: 
==> default: Running handlers:
==> default: [2016-01-15T21:13:44+00:00] INFO: Running report handlers
==> default: Running handlers complete
==> default: [2016-01-15T21:13:44+00:00] INFO: Report handlers complete
==> default: Chef Client finished, 178/203 resources updated in 15 minutes 30 seconds
