### ISSUE TITLE
Error running swift-init start main

### ISSUE THREAD

**Issue by pareshpp** [swiftstack/kinetic-swift#62]
I followed exact steps to deploy kinetic-swift given on the link 
https://github.com/swiftstack/kinetic-swift/wiki/Deployment

I did perform all the steps successfully till the end without any error. But I am getting error while running swift-init start main as below:-

swift-init start main
Starting proxy-server...(/etc/swift/proxy-server.conf)
Starting container-server...(/etc/swift/container-server.conf)
Starting account-server...(/etc/swift/account-server.conf)
Starting object-server...(/etc/swift/object-server.conf)
bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

**Comment by clayg** [comment]
Verify that bind_port is uncommented in the default section of `/etc/swift/*-server.conf` - this should be the case following the examples if you use the version of swift in the submodule.

You can start the processes directly with `swift-*-server /etc/swift/*-server.conf verbse` and might me more information if they fail to start.

**Comment by pareshpp** [comment]
I have uncommented bind_port as below in all the config files. 


These are my config files. 
# cat /etc/swift/object-server.conf | head -3
[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 6000
# cat /etc/swift/proxy-server.conf | head -3
[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 8080
# cat /etc/swift/container-server.conf | head -3
[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 6001
# cat /etc/swift/account-server.conf | head -3
[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 6002

Still am getting the error. Copying verbose output. 

# swift-init start main verbose
Starting proxy-server...(/etc/swift/proxy-server.conf)
Starting container-server...(/etc/swift/container-server.conf)
Unable to locate config for verbose-server
Starting account-server...(/etc/swift/account-server.conf)
Starting object-server...(/etc/swift/object-server.conf)
bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

bind_port wasn't properly set in the config file. It must be explicitly set to a valid port number.

**Comment by pareshpp** [comment]
I could resolve the issue with changing the user name. Thanks anyways. Closing the issue.

**Comment by clayg** [comment]
OH!  how strange.

I filed an upstream bug -> https://bugs.launchpad.net/swift/+bug/1535839

**Comment by alanyukeroo** [comment]
@pareshpp i have same problem, and know i curios with username that you changed, what username ?

**Comment by clayg** [comment]
@alanyukeroo I think it turned out to be a permissions issue with the config file (see linked launchpad bug report)?  Like the config file was root:root 600 and services were being started as "swift" or "vagrant"?  You probably want the config files to be readable by the "user_running_swift" if you followed https://github.com/swiftstack/kinetic-swift/wiki/Deployment

**Comment by clayg** [comment]
I tried to update the deployment guide to make the user name issues a little more clear

**Comment by alanyukeroo** [comment]
[solved] my proxy-swift configuritaion was wrong, the bind_port line and another command in proxy-swift.conf have a space in front of it, then i deleted the space. now proxy-server can run without problem, btw thanks reply :+1:
