### ISSUE TITLE
Object HEAD failed while uploading object

### ISSUE THREAD

**Issue by pareshpp** [swiftstack/kinetic-swift#63]
On one Ubuntu machine [freshly installed] I carried out steps listed in the link below. 

https://github.com/swiftstack/kinetic-swift/wiki/Deployment#configuring-swift

I could get all the swift services up and running. stat, list and post command worked fine for me as below
swift -U test:tester -K testing -A http://192.168.122.1:8080/auth/v1.0 stat
        Account: AUTH_test
     Containers: 0
        Objects: 0
          Bytes: 0
   Content-Type: text/plain; charset=utf-8
    X-Timestamp: 1453106568.57782
     X-Trans-Id: txee8077fd5034480babf45-00569ca588
X-Put-Timestamp: 1453106568.57782

# swift -U test:tester -K testing -A http://192.168.122.1:8080/auth/v1.0  post foobar

BUT for below command I am getting error as object head failed. 
# swift -U test:tester -K testing -A http://192.168.122.1:8080/auth/v1.0  upload foobar test
Object HEAD failed: http://192.168.122.1:8080/v1/AUTH_test/foobar/test 503 Service Unavailable

Following are my configuration details:-

# swift-ring-builder /etc/swift/account.builder
/etc/swift/account.builder, build version 1
1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 1 devices, 0.00 balance, 0.00 dispersion
The minimum number of hours before a partition can be reassigned is 1
The overload factor is 0.00% (0.000000)
Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
             0       1     1       127.0.0.1  6002       127.0.0.1              6002       sdv   1.00       3072    0.00

# swift-ring-builder /etc/swift/object.builder
/etc/swift/object.builder, build version 1
1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 1 devices, 0.00 balance, 0.00 dispersion
The minimum number of hours before a partition can be reassigned is 1
The overload factor is 0.00% (0.000000)
Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
             0       1     1       127.0.0.1  6000       127.0.0.1              6000 172.20.1.9:8123   1.00       3072    0.00
# swift-ring-builder /etc/swift/container.
container.builder  container.ring.gz
root@kingfisher:~/cos# swift-ring-builder /etc/swift/container.builder
/etc/swift/container.builder, build version 1
1024 partitions, 3.000000 replicas, 1 regions, 1 zones, 1 devices, 0.00 balance, 0.00 dispersion
The minimum number of hours before a partition can be reassigned is 1
The overload factor is 0.00% (0.000000)
Devices:    id  region  zone      ip address  port  replication ip  replication port      name weight partitions balance meta
             0       1     1       127.0.0.1  6001       127.0.0.1              6001       sdv   1.00       3072    0.00

# cat /etc/swift/account-server.conf | head -3
[DEFAULT]
#bind_ip = 127.0.0.1
bind_port = 6002
# cat /etc/swift/container-server.conf | head -3
[DEFAULT]
#bind_ip = 127.0.0.1
bind_port = 6001
# cat /etc/swift/proxy-server.conf | head -3
[DEFAULT]
#bind_ip = 127.0.0.1
bind_port = 8080

**Comment by clayg** [comment]
I think three replicas on one device is going to have a bad time.  You should reduce your replica count or add more devices.

The interesting details of the 503 response will be in proxy and object logs - sent to /var/log/syslog by default.
